spring:
  application:
    name: reservations
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/reservations}
    username: ${DB_USER:coderik}
    password: ${DB_PASSWORD:4455}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

cors:
  origin: ${FRONT_END_URL:http://localhost:4200/}
server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: native