spring:
  application:
    name: reservations
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/reservations}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

cors:
  origin: ${FRONT_END_URL:http://localhost:4200/}
server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: native

api:
  secret:
    security:
      token:
        secret: ${DB_PASSWORD:tKx3+FZk6rW8xMRfXxskAc9sboeR0Pj84aEJ08zoZ9po2cxTjHnA4t5GToWw6m7bM1fUcq6bqAoW7r3QkA8q0w==}